language: objective-c
sudo: false
xcode_workspace: isNamyang.xcworkspace
xcode_scheme: isNamyang
xcode_destination: platform=iOS Simulator,OS=13.2.2,name=iPhone 11
osx_image: xcode11.2
install:
  - gem update cocoapods
  - pod install
  - brew install swiftformat
before_script:
  - swiftformat --lint .
  - cp ./isNamyang/mock-GoogleService-Info.plist ./isNamyang/GoogleService-Info.plist
